apiVersion: 1

datasources:
  - name: local-prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090  # Docker container name for Prometheus
    basicAuth: false
    isDefault: true
    editable: true
